[project]
name = "sesame-attack"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "mitreattack-python>=5.2.1",
]

[dependency-groups]
dev = [
    "black>=25.11.0",
]
